apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstapp
  namespace: labgke
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: web
        image: us-east1-docker.pkg.dev/sincere-pixel-339218/myfirstapp/myfirstapp:2.0
        env:
        - name: REDIS_HOST
          value: 127.0.0.1
        - name: MESSAGE
          value: "labGKE - Stephanie Dangelo" 
        ports:
        - name: http
          containerPort: 80
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
